import tkinter
root=tkinter.Tk()
root.geometry("600x400")
l1=tkinter.Label(root,text="Number Addition Program",font="Aria 10 bold")
l2=tkinter.Label(root,text="First no.")
l3=tkinter.Label(root,text="second no.")
e1=tkinter.Entry(root)
e2=tkinter.Entry(root)
b1=tkinter.Button(root,text="Add")
b2=tkinter.Button(root,text="clear")
b3=tkinter.Button(root,text="Quit")
l1.grid(row=0,column=0,columnspan=3)
l2.grid(row=1,column=0)
l3.grid(row=2,column=0)
e1.grid(row=1,column=1)
e2.grid(row=2,column=1)
b1.grid(row=3,column=0)
b2.grid(row=3,column=1,sticky=tkinter.E+tkinter.W)
b3.grid(row=3,column=2)
root.mainloop()